dist: trusty
language: rust
rust: nightly
services: docker
sudo: required

env:
  - TARGET=x86_64-unknown-linux-gnu
  - TARGET=i686-unknown-linux-gnu
  - TARGET=mips-unknown-linux-gnu
  - TARGET=mips64-unknown-linux-gnuabi64

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION
  - source ~/.cargo/env
  - "[ $TARGET = x86_64-unknown-linux-gnu ] || rustup target add $TARGET"
  - cargo install --debug cross

script:
  - cd zbuf
  - cargo generate-lockfile
  - cross test --target $TARGET
