[package]
name = "zbuf"
version = "0.1.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT/Apache-2.0"
description = "“Zero-copy” string and bytes buffers"

[lib]
path = "lib.rs"

[dependencies]
